# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 605e7b2481b2fc98b8af790995cbee58a952afc1d9e4e773aefbc1014a9151183534fb7fc5a9c0454d65bcaa7637c83c13efbf55c2911d64962fce991f6e291a

test:
  secret_key_base: d22b3f09a2c90c0064afec9f9e6b5a6ba6c28732b5926290c2c18347809ab98769c42af47f0daecb5de3e64d5f76f681860736d1be31005af4306f4e4b966dd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
